version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/annotations" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/processor" # Location of package manifests
    schedule:
      interval: "daily"
